// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG7opqK8A88h_u3OvPVkwSEqyMSly9uB8',
    appId: '1:647503704188:web:f66a49ad6885f243be19f9',
    messagingSenderId: '647503704188',
    projectId: 'chat-app-66f1c',
    authDomain: 'chat-app-66f1c.firebaseapp.com',
    storageBucket: 'chat-app-66f1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4QHg1iG5sztj5J0Xc1RAFqRzvAJ5yjyE',
    appId: '1:647503704188:android:0afc56b91a901e12be19f9',
    messagingSenderId: '647503704188',
    projectId: 'chat-app-66f1c',
    storageBucket: 'chat-app-66f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlUAHh7WWyKgBck8XClguG2-d5UoyvQk',
    appId: '1:647503704188:ios:503cbaea941cae56be19f9',
    messagingSenderId: '647503704188',
    projectId: 'chat-app-66f1c',
    storageBucket: 'chat-app-66f1c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGlUAHh7WWyKgBck8XClguG2-d5UoyvQk',
    appId: '1:647503704188:ios:503cbaea941cae56be19f9',
    messagingSenderId: '647503704188',
    projectId: 'chat-app-66f1c',
    storageBucket: 'chat-app-66f1c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG7opqK8A88h_u3OvPVkwSEqyMSly9uB8',
    appId: '1:647503704188:web:2c4f3a06fc1c6bafbe19f9',
    messagingSenderId: '647503704188',
    projectId: 'chat-app-66f1c',
    authDomain: 'chat-app-66f1c.firebaseapp.com',
    storageBucket: 'chat-app-66f1c.firebasestorage.app',
  );
}
